frase='Curso em Video Python'
print(frase[9:21:2])
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,14))
print(frase.find('deo'))
print(frase.find('android'))
print('Curso'in frase)
print(frase.replace('Python','Android'))
print(frase.upper())
print(frase.lower())
print(frase.title())
print(frase.capitalize())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
div = frase.split()
print(div[0])
div2 = frase.split()
print(div2[2][3])
frase = (frase.split())
print(' '.join(frase))
print(' - '.join(frase))
